import { ScheduledExpenseRepository } from "@/repositories/scheduled-expense.repository";
import { TransactionRepository } from "@/repositories/transaction.repository";
import { CategoryRepository } from "@/repositories/category.repository";
import { GamificationQueue } from "@/queue/gamification.queue";
import { ReminderBadgeQueue } from "@/queue/reminder-badge.queue";
import { redisClient } from "@/config/redis";
import { AnalysisMLService } from "./analysis-ml.service";
import { UserSettingService } from "./user-setting.service";
import { CategoryMap } from "@/constants/app";
import logger from "@/utils/winston.logger";
import { CreateScheduledExpense, UpdateScheduledExpense } from "@/schemas/scheduled-expense.schema";

export class ScheduledExpenseService {
    private repo = new ScheduledExpenseRepository();
    private txRepo = new TransactionRepository();
    private categoryRepo = new CategoryRepository();
    private gamificationQueue = new GamificationQueue();
    private reminderBadgeQueue = new ReminderBadgeQueue();

    public getAll = async (userId: string) => {
        return this.repo.getAll(userId);
    }

    public getById = async (id: string, userId: string) => {
        const expense = await this.repo.getById(id);
        if (!expense || expense.userId !== userId) return null;
        return expense;
    }

    public create = async (data: CreateScheduledExpense) => {
        return this.repo.create(data);
    }

    public update = async (id: string, userId: string, data: UpdateScheduledExpense) => {
        const expense = await this.repo.getById(id);
        if (!expense || expense.userId !== userId) return null;
        return this.repo.update(id, data);
    }

    public delete = async (id: string, userId: string) => {
        const expense = await this.repo.getById(id);
        if (!expense || expense.userId !== userId) return false;
        await this.repo.delete(id);
        return true;
    }

    public approve = async (id: string, userId: string) => {
        const expense = await this.repo.getById(id);
        if (!expense || expense.userId !== userId) return null;

        const now = new Date();
        const transaction = await this.txRepo.create(expense.userId, {
            description: expense.description,
            amount: expense.amount,
            type: 'EXPENSE',
            date: now,
            categoryId: expense.categoryId || undefined,
        });

        await this.repo.markProcessed(id, now);

        this.fireAndForgetSideEffects(expense.userId, transaction.id, expense.description);

        return transaction;
    }

    private async fireAndForgetSideEffects(userId: string, transactionId: string, description: string) {
        try {
            if (description) {
                const settings = await UserSettingService.getSettings(userId);
                const isAutoCategorizeEnabled = settings?.autoCategorize ?? true;

                if (isAutoCategorizeEnabled) {
                    const mlResult = await AnalysisMLService.runPipelineV2(
                        [{ id: transactionId, description }],
                        1,
                        0.5
                    );

                    if (mlResult && mlResult.predictions.length > 0) {
                        const pred = mlResult.predictions[0];
                        const matchedMeta = CategoryMap[pred.predictedCategory];

                        const category = await this.categoryRepo.upsertByUserAndName({
                            userId,
                            name: pred.predictedCategory,
                            type: 'EXPENSE',
                            color: matchedMeta?.color ?? "#888888",
                            icon: matchedMeta?.icon ?? "Ellipsis",
                            isAutoGenerated: true,
                            aiConfidence: pred.confidence,
                            aiKeywords: [pred.predictedCategory.toLowerCase()]
                        });

                        const updateData: any = { categoryId: category.id };
                        if (pred.reviewRequired) {
                            updateData.needsReview = true;
                        }
                        await this.txRepo.update(userId, transactionId, updateData);
                    }
                }
            }

            redisClient?.del(`dashboard:${userId}`);

            await this.gamificationQueue.add('update-gamification', {
                userId,
                action: 'TRANSACTION_CREATED',
                value: 1,
            });

            await this.reminderBadgeQueue.add('cek-budget', { userId });
        } catch (err) {
            logger.warn("Failed scheduled expense approve side effects:", err);
        }
    }
}
