export const CLUSTER_COLORS = [
    '#6366f1', '#10b981', '#f59e0b', '#3b82f6',
    '#ef4444', '#8b5cf6', '#ec4899', '#14b8a6',
];

export const CATEGORIES = [
    'Pengiriman',
    'Administrasi & Dokumen',
    'ATK & Percetakan',
    'Kendaraan',
    'Investasi Properti',
    'Pajak',
    'Tempat Tinggal',
    'Keluarga',
    'Kebersihan & Toiletries',
    'Tabungan & Investasi',
    'Gaming',
    'Hadiah',
    'Pernikahan & Event',
    'Sosial & Komunitas',
    'Bisnis & Usaha',
    'Hiburan',
    'Donasi/Zakat',
    'Cicilan & Utang',
    'Kesehatan',
    'Pakaian',
    'Transfer & Topup',
    'Gadget & Elektronik',
    'Pendapatan',
    'Hewan Peliharaan',
    'Langganan Digital',
    'Biaya Darurat',
    'Asuransi',
    'Tagihan',
    'Pendidikan',
    'Jasa Profesional',
    'Biaya Admin & Bank',
    'Liburan',
    'Perlengkapan Rumah',
    'Perbaikan & Maintenance',
    'Makanan & Minuman',
    'Olahraga & Fitness',
    'Parkir & Tol',
    'Hobi',
    'Belanja Harian',
    'Perawatan Diri',
    'Transportasi',
    'Pulsa & Data'
];