export interface User {
    id: string;
    email: string;
    name: string;
    avatar?: string;
    createdAt: string;
    level?: number;
    streak?: number;
    badgeCount?: number;
}

export interface AuthState {
    user: User | null;
    isAuthenticated: boolean;
    setAuth: (user: User) => void;
    logout: () => void;
    updateUser: (user: Partial<User>) => void;
}

export interface LoginCredentials {
    email: string;
    password: string;
}

export interface RegisterData {
    name: string;
    email: string;
    password: string;
    confirmPassword: string;
}

export type TransactionType = 'INCOME' | 'EXPENSE';

export type TransactionSource = 'MANUAL' | 'CSV_IMPORT' | 'API';

export interface Transaction {
    id: string;
    userId: string;
    description: string;
    amount: number;
    type: TransactionType;
    date: string;
    categoryId?: string;
    clusterId?: string;
    source: TransactionSource;
    createdAt: string;
    updatedAt: string;
    category?: Category;
}

export interface Category {
    id: string;
    userId: string;
    name: string;
    color: string;
    icon?: string;
    isAutoGenerated: boolean;
    aiConfidence?: number;
    aiKeywords: string[];
    createdAt: string;
    updatedAt: string;
}

export type BudgetPeriod = 'WEEKLY' | 'MONTHLY' | 'YEARLY';

export interface BudgetGoal {
    id: string;
    userId: string;
    categoryId: string;
    amount: number;
    period: BudgetPeriod;
    alertThreshold: number;
    createdAt: string;
    updatedAt: string;
    category?: Category;
    spent?: number;
}

export interface UserStats {
    id: string;
    userId: string;
    xp: number;
    level: number;
    streak: number;
    longestStreak: number;
    totalTransactions: number;
    totalIncome: number;
    totalExpense: number;
}

export interface DashboardSummary {
    totalBalance: number;
    monthlyIncome: number;
    monthlyExpense: number;
    savingsRate: number;
    recentTransactions: Transaction[];
    topCategories: CategorySpend[];
}

export interface CategorySpend {
    categoryId: string;
    categoryName: string;
    color: string;
    amount: number;
    percentage: number;
    transactionCount: number;
}

export interface MonthlyData {
    month: string;
    income: number;
    expense: number;
    balance: number;
}

export interface AnalysisResult {
    id: string;
    status: 'running' | 'completed' | 'failed';
    kOptimal?: number;
    silhouetteScore?: number;
    clusters: ClusterResult[];
    totalTransactions: number;
    durationMs?: number;
    createdAt: string;
}

export interface ClusterResult {
    id: string;
    name: string;
    suggestedName?: string;
    color: string;
    transactionCount: number;
    totalAmount: number;
    silhouetteScore?: number;
}

export type NavItem = {
    label: string;
    href: string;
    icon: string;
};

export type ToastType = 'success' | 'error' | 'warning' | 'info';

export interface ApiResponse<T> {
    data: T;
    message: string;
    success: boolean;
}

export interface PaginatedResponse<T> {
    data: T[];
    total: number;
    page: number;
    limit: number;
    totalPages: number;
}

export interface TransactionFilter {
    type?: TransactionType;
    categoryId?: string;
    startDate?: string;
    endDate?: string;
    search?: string;
    page?: number;
    limit?: number;
}

export interface UserResponse {
    name: string;
    email: string;
    password: string;
    id: string;
    avatar: string | null;
    createdAt: Date;
    updatedAt: Date;
}

export interface ErrorResponse {
    message: string;
    success: boolean;
}