import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import axiosClient from "@/lib/api/client";

export interface Category {
    id: string;
    userId: string;
    name: string;
    color: string;
    icon: string | null;
    type: 'EXPENSE' | 'INCOME';
    isAutoGenerated: boolean;
    createdAt: string;
    updatedAt: string;
}

export function useCategories() {
    const queryClient = useQueryClient();

    const query = useQuery({
        queryKey: ['categories'],
        queryFn: async () => {
            const res = await axiosClient.get("/categories");
            return (res.data as Category[]) || [];
        },
        initialData: []
    });

    const createMutation = useMutation({
        mutationFn: async (data: { name: string, type: 'EXPENSE' | 'INCOME', icon?: string }) => {
            const res = await axiosClient.post("/categories", data);
            return res.data;
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['categories'] });
        }
    });

    return {
        categories: query.data,
        isLoading: query.isLoading,
        error: query.error,
        createCategoryAsync: createMutation.mutateAsync,
        isCreating: createMutation.isPending
    };
}
