import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import axiosClient from "@/lib/api/client";
import { addPendingMutation, cacheResponse, getCachedResponse } from "@/lib/offline/db";

export interface Category {
    id: string;
    userId: string;
    name: string;
    color: string;
    icon: string | null;
    type: 'EXPENSE' | 'INCOME';
    isAutoGenerated: boolean;
    createdAt: string;
    updatedAt: string;
}

export function useCategories() {
    const queryClient = useQueryClient();

    const query = useQuery({
        queryKey: ['categories'],
        queryFn: async () => {
            try {
                const res = await axiosClient.get("/categories");
                const data = (res.data as Category[]) || [];
                await cacheResponse('/api/categories', data);
                return data;
            } catch (error) {
                const cached = await getCachedResponse('/api/categories');
                if (cached) {
                    console.log('[Categories] Serving from offline cache');
                    return cached.data as Category[];
                }
                throw error;
            }
        },
        initialData: []
    });

    const createMutation = useMutation({
        mutationFn: async (data: { name: string, type: 'EXPENSE' | 'INCOME', icon?: string }) => {
            if (!navigator.onLine) {
                const offlineId = `offline_cat_${Date.now()}`;
                await addPendingMutation({
                    id: offlineId,
                    action: "CREATE",
                    data,
                    endpoint: "/categories",
                });
                return { ...data, id: offlineId, isOffline: true } as any;
            }
            const res = await axiosClient.post("/categories", data);
            return res.data;
        },
        onMutate: async (newCategory) => {
            await queryClient.cancelQueries({ queryKey: ['categories'] });
            const previousCategories = queryClient.getQueryData(['categories']);

            const optimisticCategory = {
                id: `temp_${Date.now()}`,
                name: newCategory.name,
                type: newCategory.type,
                icon: newCategory.icon || null,
                color: "#6b7280",
                userId: "",
                isAutoGenerated: false,
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
                isOffline: !navigator.onLine,
            };

            queryClient.setQueryData(['categories'], (old: any) => {
                if (!old) return [optimisticCategory];
                return [...old, optimisticCategory];
            });

            return { previousCategories };
        },
        onSuccess: (data) => {
            if (data && (data as any).isOffline) {
                // Silent success for offline
            } else {
                queryClient.invalidateQueries({ queryKey: ['categories'] });
            }
        },
        onError: (error, _, context) => {
            if (context?.previousCategories) {
                queryClient.setQueryData(['categories'], context.previousCategories);
            }
        }
    });

    return {
        categories: query.data,
        isLoading: query.isLoading,
        error: query.error,
        createCategoryAsync: createMutation.mutateAsync,
        isCreating: createMutation.isPending
    };
}
