import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import axiosClient from "@/lib/api/client";
import { saveToLocal, cacheResponse, getCachedResponse, mergePendingMutations, checkOnlineStatus } from "@/lib/offline/db";
import { useAuthStore } from "@/lib/zustand/auth-store";

export interface Category {
    id: string;
    userId: string;
    name: string;
    color: string;
    icon: string | null;
    type: 'EXPENSE' | 'INCOME';
    isAutoGenerated: boolean;
    createdAt: string;
    updatedAt: string;
}

export function useCategories() {
    const queryClient = useQueryClient();
    const { user } = useAuthStore();
    const userId = user?.id || "guest";

    const query = useQuery({
        queryKey: ['categories'],
        queryFn: async () => {
            try {
                const res = await axiosClient.get("/categories");
                const data = (res.data as Category[]) || [];
                await cacheResponse(userId, '/api/categories', data);
                return data;
            } catch (error) {
                const cached = await getCachedResponse(userId, '/api/categories');
                if (cached) {
                    console.log('[Categories] Serving from offline cache');
                    const merged = await mergePendingMutations(userId, cached.data, "/categories");
                    return merged as Category[];
                }
                throw error;
            }
        },
        initialData: []
    });

    const createMutation = useMutation({
        mutationFn: async (data: { name: string, type: 'EXPENSE' | 'INCOME', icon?: string }) => {
            const record = await saveToLocal(userId, {
                action: "CREATE",
                data,
                endpoint: "/categories",
            });

            if (navigator.onLine) {
                try {
                    const res = await axiosClient.post("/categories", data);
                    const { updateRecordStatus } = await import("@/lib/offline/db");
                    await updateRecordStatus(userId, record.id, "synced");
                    return res.data;
                } catch {
                    return { ...data, id: record.id, isPending: true } as any;
                }
            }

            return { ...data, id: record.id, isPending: true } as any;
        },
        onMutate: async (newCategory) => {
            await queryClient.cancelQueries({ queryKey: ['categories'] });
            const previousCategories = queryClient.getQueryData(['categories']);

            const optimisticCategory = {
                id: `temp_${Date.now()}`,
                name: newCategory.name,
                type: newCategory.type,
                icon: newCategory.icon || null,
                color: "#6b7280",
                userId: "",
                isAutoGenerated: false,
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
                isOffline: !navigator.onLine,
            };

            queryClient.setQueryData(['categories'], (old: any) => {
                if (!old) return [optimisticCategory];
                return [...old, optimisticCategory];
            });

            return { previousCategories };
        },
        onSuccess: (data) => {
            if (data && (data as any).isPending) {
                // Silent success for offline
            } else {
                queryClient.invalidateQueries({ queryKey: ['categories'] });
            }
        },
        onError: (error, _, context) => {
            if (context?.previousCategories) {
                queryClient.setQueryData(['categories'], context.previousCategories);
            }
        }
    });

    return {
        categories: query.data,
        isLoading: query.isLoading,
        error: query.error,
        createCategoryAsync: createMutation.mutateAsync,
        isCreating: createMutation.isPending
    };
}
