import prisma from "@/config/prisma";
import { TransactionType } from "generated/prisma/enums";

export class CategoryRepository {
    public getAll = async (userId: string) => {
        return prisma.category.findMany({
            where: { userId },
            orderBy: { name: 'asc' }
        });
    }

    public findByIds = async (ids: string[]) => {
        return prisma.category.findMany({
            where: {
                id: { in: ids }
            }
        });
    }

    public create = async (data: { userId: string, name: string, color?: string, icon?: string, type: TransactionType }) => {
        return prisma.category.create({
            data: {
                userId: data.userId,
                name: data.name,
                color: data.color || "#888888",
                icon: data.icon,
                type: data.type
            }
        });
    }

    public upsertByUserAndName = async (data: { userId: string, name: string, type: TransactionType, color?: string, icon?: string, isAutoGenerated: boolean, aiConfidence: number | null, aiKeywords: string[] }) => {
        return prisma.category.upsert({
            where: {
                userId_name: {
                    userId: data.userId,
                    name: data.name
                }
            },
            update: {
                color: data.color,
                icon: data.icon,
                isAutoGenerated: data.isAutoGenerated,
                aiConfidence: data.aiConfidence,
                aiKeywords: data.aiKeywords
            },
            create: {
                userId: data.userId,
                name: data.name,
                color: data.color || "#888888",
                icon: data.icon,
                isAutoGenerated: data.isAutoGenerated,
                aiConfidence: data.aiConfidence,
                aiKeywords: data.aiKeywords,
                type: data.type
            }
        });
    }

    public deleteAutoGeneratedByUser = async (userId: string) => {
        return prisma.category.deleteMany({
            where: {
                userId,
                isAutoGenerated: true,
            }
        });
    }
}